### ISSUE TITLE
Make available through pypi

### ISSUE THREAD

**Issue by nickpolet** [erdem/django-admino#7]
At the moment, this package requires you to install by cloning into your project folder. To make this easier to install and to make installation through automated scripts easier (installing onto servers with requirements.txt or similar), it would be nice if this could be made into a proper python package.

**Comment by erdem** [comment]
Hi @nickpolet 

I submitted the package to PyPI and I updated the documentation. You can install admino from `pip` or you can use setup.py.

`pip install django-admino`

Thanks
