### ISSUE TITLE
Moving this repo to jazzband

### ISSUE THREAD

**Issue by sideffect0** [erdem/django-admino#8]
jazzband is a group of devs maintains many django related projects, this project seems like a good one that needs care, you agree with this suggestion ?
if so i could open an issue ther 😄 
jazzband : https://github.com/jazzband

**Comment by erdem** [comment]
Hi 

Thank you for interest the project but we are not considering to join any group at the moment. This project was a hackathon project and we have many milestones and plan for this project. Maybe we can consider when we are released first stable version.
